### ISSUE TITLE
How are S8 and sigma8 calculated in CLASS-PT

### ISSUE THREAD

**Issue by alexander-reeves** [Michalychforever/CLASS-PT#6]
Dear all, 

I have been using CLASS-PT to analyse an early dark energy extension to LCDM. The matter power spectra computed using 1-loop PT in CLASS-PT differs (as expected) from the MPS computed using linear perturbation theory in CLASS-EDE. However, when I get class to output the sigma8 and S8 parameters in both setups I get very similar values for the same input parameters- leading me to think that the calculation of these parameters doesn't take into account non-linear corrections; is there a way to include these corrections and output the corresponding values of S8 and sigma8 using CLASS-PT? 

Thank you!

Alex

**Comment by Michalychforever** [comment]
Hi Alex,

There is no contradiction here. By definition sigma8 is the amplitude of *linear* mass fluctuations, and thus it does not depend on nonlinear corrections (same for S8).

**Comment by alexander-reeves** [comment]
Ah, I see- thank you very much!
